remote_theme: pages-themes/hacker@v0.2.0

plugins:
  - jekyll-remote-theme

title: "B7ZK — Osmar D."
description: "Backend Developer • Node.js • PostgreSQL • DevOps Journey"

# Opcional: enlaces útiles del footer
github:
  owner_url: "https://github.com/b7zk"
  repo_url: "https://github.com/b7zk/b7zk.github.io"

# Opcional, cambiar favicon
favicon: "/assets/favicon.ico"